### ISSUE TITLE
storing password outside of dbconfig.yml?

### ISSUE THREAD

**Issue by dwburke** [rubenv/sql-migrate#119]
at the moment the only way I see to handle database passwords is to either not store my dbconfig.yml in git (less than ideal), or commit my password to revision control (also not ideal).

Is there a recommended workaround?

Thanks,
Dan.

**Comment by v47** [comment]
For postgres I just set up `PGPASSWORD` env var and everything works perfectly.

**Comment by dwburke** [comment]
oh, I'll try this and come back, thanks!

**Comment by dwburke** [comment]
that works perfectly, thanks!

I checked the docs for other env vars and moved most of the connection settings out, and documented what env vars were required for my app... that'll be much cleaner going forward...

**Comment by SashaOv** [comment]
Any suggestions for MySQL users? I couldn't find a way to use environment variables for MySQL driver.
