### ISSUE TITLE
Call to github.com/gobuffalo/packr#Box.Bytes yields deprecation warning

### ISSUE THREAD

**Issue by aeneasr** [rubenv/sql-migrate#121]
When using `migrate.PackrMigrationSource`, this error shows up:

```
[DEPRECATED] github.com/gobuffalo/packr#Box.Bytes has been deprecated.
        Use github.com/gobuffalo/packr#Box.Find instead.
```

**Comment by rubenv** [comment]
Would you mind sending a PR that fixes this?

**Comment by aeneasr** [comment]
Extremely busy right now, if I find some free time I'll try, but you'll probably be able to solve this in much shorter time :)

**Comment by rubenv** [comment]
Am currently travelling and not anywhere near a computer, so sadly not :-)

**Comment by rubenv** [comment]
Thanks a lot, appreciate the kind words! 

Spread the love!
