### ISSUE TITLE
How do you apply your migrations

### ISSUE THREAD

**Issue by alok87** [rubenv/sql-migrate#125]
We run our service in kubernetes.
What is the right way to execute migrations using `sql-migrate` as part of deployment to kubernetes.

We need to have `sql-migrate` binary in our Dockerfile or entrypoint?

**Comment by alok87** [comment]
We don't use `packer`. Then do I need to make the binary be part of Docker image and then execute the binary in the entrypoint to apply migrations? Then i need to copy migration files also in Dockerfile also

**Comment by rubenv** [comment]
Note the missing e: packr, not packer.

Check the README in this repo for instructions on how to use it as a
library.

**Comment by alok87** [comment]
Thanks let me try out.
