### ISSUE TITLE
support to turn off transactions per migration

### ISSUE THREAD

**Issue by dre1080** [rubenv/sql-migrate#13]
There are SQL Queries that can't run inside a transaction. Since all Migrations run inside a transaction there is no way to run these queries within a migration. (Eg. creating concurrent indices with postgres  http://www.postgresql.org/docs/9.3/static/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY)

Maybe by adding a `-- +migrate DisableTransaction` or a `-- +migrate DisableTx` comment.

**Comment by dre1080** [comment]
@rubenv Any more updates on this?

**Comment by rubenv** [comment]
Pull requests welcome, haven't had the need nor time to do this myself.

**Comment by bobbytables** [comment]
Yeah this is really needed. Postgres can't do things such as adding values to enum types.

**Comment by rubenv** [comment]
I have no immediate need or plans to add this, but I'll happily review /
merge a good pull request.

**Comment by Dynom** [comment]
@rubenv, @russellhaering took the time to write a PR (#35) to support this. Can you look at it?
