### ISSUE TITLE
Use newer packr

### ISSUE THREAD

**Issue by janekolszak** [rubenv/sql-migrate#144]
Hi!
Maybe it's time to use packr v2?

https://github.com/gobuffalo/packr/tree/master/v2

Thanks!

**Comment by rubenv** [comment]
Sure! What changes would that require?

Sql-migrate has no direct dependency on packr, we have an interface that
mimicks the needed methods.

**Comment by codestation** [comment]
Added a pull request that updates the readme and tests. The methods used in the interface are unchanged so there are no changes in the source.

Also packr is using go modules with directories so users that aren't using modules can use the new version without problems.
