### ISSUE TITLE
Love the tool, but...

### ISSUE THREAD

**Issue by marcelloh** [rubenv/sql-migrate#148]
Look at this:
https://goreportcard.com/report/github.com/rubenv/sql-migrate
Some low hanging fruit you can easily fix.

or should I?
But I'm afraid I spend time and it won't get in the release (since there are others waiting to have their pull request in...)

Anyway, keep up the good work!

**Comment by rubenv** [comment]
Go for it!

I'll happily merge it if it doesn't break things.

Most of those are false-positives though, for instance:

```
Line 13: warning: exported method DownCommand.Help should have comment or be unexported (golint)
```

You really don't need a comment on a type that's only used by the CLI tool. That's just a waste of energy and it's not like anyone will ever use that type as a library.

**Comment by rubenv** [comment]
Do keep the pull requests small and focused, 10 PRs of 10 lines have a much higher chance of getting in than 1 PR of 100 lines.

**Comment by marcelloh** [comment]
it's there. and you could merge file by file and look at the comments. I did a best guess ;-)
