### ISSUE TITLE
Support predeclared Go types in type overrides

### ISSUE THREAD

**Issue by ean** [rubenv/sql-migrate#161]
I am using the postgres [citext](https://www.postgresql.org/docs/11.0/citext.html) extension in my code, and would like to map the `citext` type to a `string` value (I am using it with NOT NULL). But this is explicitly forbidden in the override parse code here: https://github.com/kyleconroy/sqlc/blob/79ec91489719ebcef55b61e07b0083821462dfa3/internal/dinosql/config.go#L103 , which requires both a `.` and `/` in the go type.

**Comment by rubenv** [comment]
I'm not following. What does this have to do with sql-migrate?

**Comment by ean** [comment]
Absolutely nothing, I am apparently just not able to create issues in the correct project today. Sorry about the noise.

**Comment by rubenv** [comment]
No worries, just blame it on today being a Sunday!
