### ISSUE TITLE
can't create table "GORP_MIGRATIONS" in oracle database 12.2.0.1-ee

### ISSUE THREAD

**Issue by fanpei91** [rubenv/sql-migrate#163]
oracle database 12.2.0.1-ee does not support `if not exists`, so it will report `ORA-00922: missing or invalid option` when `migrate.Exec(db, "oci8", migrations, migrate.Up)`

By the way, oracle database 12.2.0.1-ee doesn't support `text` type.

ref:
![image](https://user-images.githubusercontent.com/5484841/73997091-7f6e1980-4998-11ea-81f8-6d45782dc9d5.png)

**Comment by rubenv** [comment]
Would you mind submitting a pull request with a fix?


Otherwise I'll have to remove Oracle support: I don't have an Oracle DB at
hand for testing.

**Comment by fanpei91** [comment]
Sure! I will try my best tomorrow.
