### ISSUE TITLE
Consider moving from packr to pkger

### ISSUE THREAD

**Issue by jufemaiz** [rubenv/sql-migrate#168]
At the moment packr/v2 (https://github.com/gobuffalo/packr/tree/master/v2) is recommending people move to use http://github.com/markbates/pkger.

Perhaps this could be explored?

**Comment by rubenv** [comment]
Note that there isn't any packr dependency in `sql-migrate`, we just have a minimal interface that mimics the type, to avoid the run-time dependency.

I'm happy to accept a PR that adds a `PkgrMigrationSource`.

**Comment by rubenv** [comment]
But obviously, in the interest of backwards compatibility, we can't remove the `PackrMigrationSource`. Not a problem though, as it's just a small wrapper: https://github.com/rubenv/sql-migrate/blob/64f95ea68aa39b024c83a7d0d60910dbdafcfb04/migrate.go#L334-L389

Shouldn't be hard to build the same thing for pkger.

**Comment by jufemaiz** [comment]
Sorry for the delayed response @rubenv (and thanks for a great package!). A little more investigation revealed that you've essentially already got the support able to be achieved (thanks in part to your solution, and the new pkger approach being adopted).

```go
migDir := pkger.Dir("/db/migrations/")

migrations := &migrate.HttpFileSystemMigrationSource{
	FileSystem: migDir,
}

migrate.SetTable("migrations")
migrate.Exec(db, "postgres", migrations, migrate.Up)
```

**Comment by rubenv** [comment]
Ah that's great to hear.

Perhaps we should add a small section to the README?
