### ISSUE TITLE
Way to use with unittests

### ISSUE THREAD

**Issue by hound672** [rubenv/sql-migrate#184]
Hello.
Does anybody try to use this lib with unittests?
Like Django, for example.
1. Start unittest
2. Up migrations for db
3. Running unittest
4. Down migrations

**Comment by rubenv** [comment]
I do, all the time. You might find a helper like this useful:
https://github.com/rubenv/pgtest

**Comment by hound672** [comment]
Thanks. But it does not up/down migrations.

**Comment by rubenv** [comment]
No but it does provide you with a clean server to test against. Doing the
up/down is just a matter of calling the library.

**Comment by hound672** [comment]
I'd like to create db by my own.
For example, I have 2 environments in `dbconfig.yml`:
1. testing
2. develop
with different credentials, db name etc.

Could I up/down migrations in golang unittests with this config (with `testing` env)?

**Comment by rubenv** [comment]
The config file is for the CLI tool, but you can do anything the CLI does
with the library.

**Comment by hound672** [comment]
Ok, thanks. I will try in this way.
