### ISSUE TITLE
Please use gopkg.in/gorp.v1

### ISSUE THREAD

**Issue by GeertJohan** [rubenv/sql-migrate#19]
I see that you are importing `gorp` from `github.com/go-gorp/gorp`.
This is the unstable "bleeding edge" version. We are working on breaking changes, it is likely that your program will fail to compile unless you update your code to reflect the changes.

Please use `gopkg.in/gorp.v1` as import path, it provides the last stable gorp v1 release and will not break (unless a breaking change is required to fix a security issue).

When the changes to the master branch are complete, v2 will be released. See go-gorp/gorp#270 for more information.
Thanks.

**Comment by rubenv** [comment]
Make sense, done!

Thanks for the heads up

**Comment by GeertJohan** [comment]
No problem, make sure to check gorp v2 when it's released, good improvements coming up!
