### ISSUE TITLE
Support native golang embed.FS

### ISSUE THREAD

**Issue by insidieux** [rubenv/sql-migrate#191]
**Is your feature request related to a problem? Please describe.**

Since  version 1.16 golang support native embedding with packages `embed` and `io/fs`. 

**Describe the solution you'd like**

Update minimal golang required version to 1.16 and provide `MigrationSource` with support `embed.FS`.
I'll provide pull request a little bit later.

**Comment by rubenv** [comment]
Also see the related #189

**Comment by insidieux** [comment]
> Also see the related #189

Ok, i've watched issue and pull. 

I have some questions:

1. Do we really need support of old golang version? 
2. I'd prefer to provide new `MigrationSource` implementation, instead of changing behaviour of previous existed. Is it ok for you?

**Comment by rubenv** [comment]
Is there a reason why we need to break compatibility with older Go versions?

**Comment by insidieux** [comment]
> Is there a reason why we need to break compatibility with older Go versions?

No, there is no suitable reasons. I've just ask your opinion. 

Would you prefer: to make me commits, comments to previous pull or send newest?

**Comment by rubenv** [comment]
> No, there is no suitable reasons. I've just ask your opinion.

Then let's not do that. We never break compatibility if we can avoid it.

> Would you prefer: to make me commits, comments to previous pull or send newest?

Let's work together on the other PR.

**Comment by insidieux** [comment]
Ok, thanks, now i'm closing this issue and provide some comments to related.
