### ISSUE TITLE
Upgrading gobuffalo/packr for compliance reasons

### ISSUE THREAD

**Issue by shubham1172** [rubenv/sql-migrate#208]
Hi, rubenv/sql-migrate depends on github.com/gobuffalo/packr/v2@v2.8.1 currently.

This issue is to upgrade the dependency to at least `v2.8.2`. Before `v2.8.2`, gobuffalo/packr depended on a really old version of github.com/spf13/cobra, which boiled down to a deprecated MPL-2.0 dependency - github.com/armon/consul-api

**Comment by rubenv** [comment]
@shubham1172 Could you send a PR? Happy to roll a new release.

**Comment by rubenv** [comment]
Merged and released as `v1.1.1`

**Comment by shubham1172** [comment]
Thanks!
