### ISSUE TITLE
Request: Update go-sqlite3 dependency to latest (1.14.14)

### ISSUE THREAD

**Issue by asartalo** [rubenv/sql-migrate#222]
Hi. SQLite3 starting from 3.35.x supports `DROP COLUMN` syntax and this comes with the latest go-sqlite3. Right now, sql-migrate uses go-sqlite3 version 1.14.6 which uses sqlite 3.34.x. It would really help making migrations with inserting/removing columns easier instead of the cumbersome method like what's written here: https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite

1. create new table as the one you are trying to change,
2. copy all data,
3. drop old table,
4. rename the new one.

**Comment by rubenv** [comment]
Sounds good, could you make a PR?

**Comment by asartalo** [comment]
Sure! Here it is: #223

**Comment by rubenv** [comment]
Merged and released as `v1.2.0`. Bumped the minor as this may incur compatibility breaks (in case someone has other tooling that's SQLite 3.34 based).

Thanks a lot!
