### ISSUE TITLE
Go install fails on Go 1.19

### ISSUE THREAD

**Issue by aminemat** [rubenv/sql-migrate#249]
Go install fails on Go 1.19

```
go install github.com/rubenv/sql-migrate/...@latest
go: github.com/rubenv/sql-migrate/...@latest (in github.com/rubenv/sql-migrate@v1.5.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by rubenv** [comment]
Time to drop Go 1.16 support then.

**Comment by rubenv** [comment]
Could you try again?

I've just release v1.5.1

**Comment by aminemat** [comment]
your responsiveness blew my mind, thank you! 
`@latest` still points to `1.5.0` 
I tried `go install github.com/rubenv/sql-migrate@1.5.1` but I'm getting `invalid version: unknown revision 1.5.1`

I'm guessing module proxy propagation?

**Comment by aminemat** [comment]
It works now, thank you so much @rubenv!

**Comment by rubenv** [comment]
Excellent, have a nice weekend!

Thanks for reporting this.
