### ISSUE TITLE
Possible release to fix build issue on Alpine Linux

### ISSUE THREAD

**Issue by pejter** [rubenv/sql-migrate#260]
https://github.com/rubenv/sql-migrate/commit/bc5e259a9623795fe565877f8b711b78a2bc2933 fixed https://github.com/mattn/go-sqlite3/issues/1164 which causes a build issue on Alpine Linux.
Is 1.6.1 release on the horizon so the fix is available?

Steps to reproduce:
1. Launch a docker container with latest golang image (golang:1.21.6-alpine3.19 as of writing this)
2. `apk add build-base`
3. `go install -v github.com/rubenv/sql-migrate/sql-migrate@v1.6.0` (this results in the error)
5. `go install -v github.com/rubenv/sql-migrate/sql-migrate@master` (github.com/mattn/go-sqlite3 v1.14.19 used, no error)

**Comment by rubenv** [comment]
Done! Thanks for the reminder!
