### ISSUE TITLE
DELIMETER breaks migrations?

### ISSUE THREAD

**Issue by lol768** [rubenv/sql-migrate#36]
**Steps to reproduce:**

```sql
-- +migrate StatementBegin
DELIMITER //
-- +migrate StatementEnd
-- +migrate StatementBegin
CREATE PROCEDURE add_system_role
  (IN name VARCHAR(20), IN display_name VARCHAR(20), IN priority INT UNSIGNED)
  BEGIN
    INSERT INTO `roles` VALUES (NULL, name, display_name, NULL, priority, DEFAULT, DEFAULT);
  END //
-- +migrate StatementEnd
-- +migrate StatementBegin
DELIMITER ;
-- +migrate StatementEnd
```

**Expected:** Procedure is created.

**Actual:** Failed to migrate the database:

```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER //\n-- +migrate StatementEnd' at line 2 handling 1_init.sql
```

**Version:** 6f4757563362064790a6687a6b60f182062c8634

We are using [jteeuwen/go-bindata](/jteeuwen/go-bindata).

**Comment by lol768** [comment]
Delimeters are client-side, misunderstood what was going on

**Comment by braeutigamj** [comment]
> Delimeters are client-side, misunderstood what was going on

I have the same issue, but I don't understand your comment. Does it mean, that sqlx-migrate does not support DELIMITER for MySQL? It works fine at a mysql shell.

Thanks in advance.
