### ISSUE TITLE
License Concern with yaml.v1

### ISSUE THREAD

**Issue by kdykeman** [rubenv/sql-migrate#50]
The license associated with yaml.v1 is [LGPLv3](https://github.com/go-yaml/yaml/blob/v1/LICENSE).  For yaml.v2, Canonical switched the license to the more permissive [Apache 2.0 license](https://github.com/go-yaml/yaml/blob/v1/LICENSE).

Any chance of updating to yaml.v2?

**Comment by rubenv** [comment]
Sure, could you send a pull request?

**Comment by rubenv** [comment]
Also, I'm not a lawyer, but as far as I can tell, this does not affect sql-migrate (or anyone using it) in any way.

The only thing LGPL requires you is to open up changes made to the `yaml` library, it has no impact on your code / application.

Nonetheless, happy to accept a PR to move to the newer version.

**Comment by srenatus** [comment]
This can be closed now, can't it?

**Comment by rubenv** [comment]
Yup!
