### ISSUE TITLE
`new command` used to month and day exchanged.

### ISSUE THREAD

**Issue by lion-man44** [rubenv/sql-migrate#65]
Hi.

Please tell me whether it is a bug or a specification.

I tried.
```sh
$ sql-migrate new -config=db/dbconfig.yml create_posts
```

output:
```sh
-rw-r--r--  1 user  staff  34  3 15 02:48 20171503024850-create_posts.sql
```

expect:
```sh
-rw-r--r--  1 user  staff  34  3 15 02:48 20170315024850-create_posts.sql
```

Why are the month and the day exchanged?

**Comment by rubenv** [comment]
BUG!

Could you send a pull request?

**Comment by lion-man44** [comment]
I'm sorry.
Sending a pull request will take a long time.
It is one hour since I started studying golang.

I understood that this code is spewing out the time of the problem, but I do not know how to fix it.

```go
// command_new.go:79
Time.Now().Format("20060201150405")
```

**Comment by lion-man44** [comment]
small case:
```
package main

import (
  "fmt"
  "time"
)

func main() {
  fmt.Printf(time.Now().Format("20060201150405"))
}
```

run:
```$
$ go run github.com/lion-man44/test.go
20171503034857%
```

**Comment by rubenv** [comment]
You're wrong, it's trivial nowadays.

Go here: https://github.com/rubenv/sql-migrate/blob/master/sql-migrate/command_new.go
And press the little pencil button:

<img width="621" alt="sql-migrate_command_new_go_at_master_ _rubenv_sql-migrate" src="https://cloud.githubusercontent.com/assets/42904/23917381/6c025d94-08ef-11e7-9cec-ae719fb1bbd4.png">

Takes about 30 seconds to get the job done!

**Comment by lion-man44** [comment]
It closes because it was merged.
