### ISSUE TITLE
Standalone tool and tests broken on MacOS/golang1.8 

### ISSUE THREAD

**Issue by KlausVii** [rubenv/sql-migrate#81]
Trying to run the standalone client on MacOS does this:
```
sql-migrate
[1]    88703 killed     sql-migrate
```

Also running the tests in rubenv/sql-migrate fail
```
src/github.com/rubenv/sql-migrate: go test ./...

signal: killed
FAIL    github.com/rubenv/sql-migrate    0.008s
signal: killed
FAIL    github.com/rubenv/sql-migrate/sql-migrate    0.007s
ok      github.com/rubenv/sql-migrate/sqlparse    0.007s
```
The culprit should be one of the last couple of commits, since I've been using this tool without issue for a while.

**Comment by KlausVii** [comment]
Found a workaround sql-migrate needs to be installed with these flags 
```go install -ldflags -s```

I think the issue was this commit: https://github.com/rubenv/sql-migrate/commit/42c30aabf72921b83678a3d0680fd6cd46682f1b
With the change from `os` to `net/http` for opening files, sql-migrate was exposed to this issue:
https://github.com/golang/go/issues/19734 where this is the solution https://github.com/golang/go/issues/11887

**Comment by rubenv** [comment]
Reading the issue, it seems that Go 1.8.1 fixes things. I'm running 1.8.3 and am not seeing issues. Could you give a newer Go a go?

**Comment by KlausVii** [comment]
Yeah I was running go1.8, seems updating to 1.8.3 solved the issue.

**Comment by rubenv** [comment]
Cool, thanks!
