### ISSUE TITLE
undefined: os.Executable

### ISSUE THREAD

**Issue by stevepm** [rubenv/sql-migrate#83]
Hi, I'm installing sql-migrate via go get and am running into an error:

```
❯ go version
go version go1.7.6 linux/amd64
```

```
❯ go get github.com/rubenv/sql-migrate/...
# github.com/posener/complete/cmd/install
go/src/github.com/posener/complete/cmd/install/install.go:75: undefined: os.Executable
```

```
❯ echo $?
2
```

This just started happening recently (past day or two).

Made a related issue here: https://github.com/posener/complete/issues/43 (feel free to close this one if you want)

**Comment by posener** [comment]
Hi @stevepm 
what is the reason not to upgrade to go1.8?

**Comment by huynguyenh** [comment]
correct me if i'm wrong and it might not relevent but i remember os.Executable is a 1.8 or newer version function

**Comment by rubenv** [comment]
Yup, time to upgrade!
