### ISSUE TITLE
Is it possible to connect to PostgreSQL using UNIX socket?

### ISSUE THREAD

**Issue by gh67uyyghj** [rubenv/sql-migrate#97]
Hello there! thanks for the great project! My postgresql is configurated in order to listen to sockets only (no tcp ports opened), is it possible to connect to postgres in that case?

**Comment by pasztorpisti** [comment]
Since sql-migrate uses the pq library for postgres my guess would be that you can use unix sockets.

[The godoc of pq](https://godoc.org/github.com/lib/pq) says it supports unix sockets. When the hostname of the datasource setting starts with / it should be treated as a domain socket.
